### ISSUE TITLE
bad result

### ISSUE THREAD

**Issue by YmanChris** [lizhi-ntu/OCKD-FacePAD#1]
Hi,I am interested in your method but I found that the result can't catch up with paper. Is the checkpoint final version?

**Comment by lizhi-ntu** [comment]
Hi, thanks for your interest in our work and open this issue. Could you provide details about which experiment you have reproduced and the results you've got. Then I'll investigate the cause of the issue.

**Comment by lizhi-ntu** [comment]
> Hi,I am interested in your method but I found that the result can't catch up with paper. Is the checkpoint final version?

Hi, thanks for your interest in our work and open this issue. Could you provide more details about which experiment you have reproduced and the results you've got. Then I'll investigate the cause of the issue.

**Comment by YmanChris** [comment]
Thanks for your reply. I use some pictures to inference respectively  by teacher and teacher-student. The preprocess is dlib. The result are blow. teacher-student :
![image](https://user-images.githubusercontent.com/18142592/176809920-8f9b5b9b-b854-4cb0-b3f0-487977667e8e.png)
Teacher:
![image](https://user-images.githubusercontent.com/18142592/176809943-be70c3fa-f573-4f15-b211-4e91f8010edc.png)

**Comment by lizhi-ntu** [comment]
> Thanks for your reply. I use some pictures to inference respectively  by teacher and teacher-student. The preprocess is dlib. The result are blow. teacher-student :
> 
> ![image](https://user-images.githubusercontent.com/18142592/176809920-8f9b5b9b-b854-4cb0-b3f0-487977667e8e.png)
> 
> Teacher:
> 
> ![image](https://user-images.githubusercontent.com/18142592/176809943-be70c3fa-f573-4f15-b211-4e91f8010edc.png)
> 
> 

The checkpoints are for C-N-CS experiments. (trained with CASIA-FASD as the source domain and NTU ROSE-YOUTU-Client as the target domain.) What dataset you use for inference?

**Comment by YmanChris** [comment]
> 

I select some attack samples in CelebA_Spoof.

**Comment by lizhi-ntu** [comment]
> > 
> 
> 
> 
> I select some attack samples in CelebA_Spoof.

You should use the same dataset for experiments at least...

**Comment by YmanChris** [comment]
> > I select some attack samples in CelebA_Spoof.
> 
> You should use the same dataset for experiments at least...

Ok. I will try it later, tkx.
