### ISSUE TITLE
怎么生成二分类得分文件

### ISSUE THREAD

**Issue by beijita-yegucheng** [lizhi-ntu/OCKD-FacePAD#3]
我想将测试集的得分生成到txt文件，可是我看代码中是求得相似度

**Comment by lizhi-ntu** [comment]
> 我想将测试集的得分生成到txt文件，可是我看代码中是求得相似度

Hello, 二分类的score就是三个level的feature的相似度的加权平均。计算方法可以参考一下 [src/algo.py](https://github.com/lizhi-ntu/OCKD-FacePAD/blob/main/src/algo.py) 214行，函数prediction_student的返回值 preds就是二分类的分数。分数越小越真。

**Comment by beijita-yegucheng** [comment]
我确实是将prediction_student的返回值 preds，可是得分都是在0.03左右，二分类得分不应该是一类是接近于1，一类接近于0吗？

**Comment by lizhi-ntu** [comment]
> 我确实是将prediction_student的返回值 preds，可是得分都是在0.03左右，二分类得分不应该是一类是接近于1，一类接近于0吗？

1) 首先，对于二分类问题，其中一个类的大多数样本score小于另一类就可以确定threshold进行二分类，跟score是否接近0或1无关。
2) 关于真假样本score都接近0。因为我们的方法在adaptation阶段只使用target domain的真样本训练student，所以测试时真假样本的score都会更接近0。但是大多数真样本的score会比假样本的score小, 可以进行二分类。

**Comment by beijita-yegucheng** [comment]
我明白了，谢谢您的及时回复与解答。十分感谢！
